language: php
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm-nightly

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

before_script:
  - phpenv config-add php.ini
  - chmod -R 777 app/cache
  - chmod -R 777 app/logs
  - chmod +x tools/console.php
  - php tools/console.php init:config
  - php tools/console.php init:sys
  - php tools/console.php cert:generate --default

services:
  - mongodb
  - redis-server
  - elasticsearch