language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add php.ini
  - composer config --global github-oauth.github.com 57bc356159615a3bdadaf926cd7f30bf9b48ffb6
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --no-interaction

before_script:
  - chmod -R 777 app/cache
  - chmod -R 777 app/logs
  - chmod +x tools/console.php
  - php tools/console.php init:config
  - php tools/console.php init:sys
  - php tools/console.php cert:generate --default

after_script:
  - php vendor/bin/coveralls -v

services:
  - mongodb
  - redis-server
  - elasticsearch