# 适配缺省 true
# everyone: 适用于 EVERYONE
# owner: 适用于 OWNER
# domain_owner: 适用于 DOMAIN_OWNER
# domain_member: 适用于 DOMAIN_MEMBER

permission:
    user:
        logout:
            everyone: false
        register:
