routing:
    index: 
        path: /
        methods: [GET]
        controller: index:index
    login:
        path: /login
        methods: [GET, POST]
        controller: index:login
    reg:
        path: /reg
        methods: [GET, POST]
        controller: index:registration