routing:
    index: 
        path: /
        methods: [GET]
        controller: index:index
    login:
        path: /login
        methods: [GET]
        controller: index:login
    login_post:
        path: /login
        methods: [POST]
        controller: index:loginPost
    logout:
        path: /logout
        methods: [GET]
        controller: index:logout
        csrf: true
    reg:
        path: /reg
        methods: [GET]
        controller: Registration:registration
    reg_send:
        path: /reg/send
        methods: [POST]
        controller: Registration:sendMail
    reg_complete:
        path: /reg/complete
        methods: [POST]
        controller: Registration:complete
    reg_verified:
        path: /reg/{token}
        methods: [GET]
        controller: Registration:verified
