services:
    vj_redirection_service:
        arguments: [@request, @response, %security.enforce_https]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\VJRedirectionService

    https_redirection_service:
        arguments: [@request, @response, %security.enforce_https]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\HttpsRedirectionService

    login_log_service:
        events: ['user.login.succeeded', 'user.login.failed.wrong_password', 'user.login.failed.user_invalid']
        class: \VJ\EventListener\LoginLogService

    vj2_credential_upgrade_service:
        events: ['user.login.succeeded']
        class: \VJ\EventListener\VJCredentialUpgradeService

    keyword_filter:
        arguments: [@redis]
        class: \VJ\Security\KeywordFilter